<a href="https://colab.research.google.com/github/MithunChevakula/Machine-Learning/blob/main/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample data
data = np.array(['red', 'blue', 'green', 'blue', 'red']).reshape(-1, 1)

# Initialize OneHotEncoder
# The 'sparse' argument has been replaced with 'sparse_output'
onehot_encoder = OneHotEncoder(sparse_output=False)

# Fit and transform the data
encoded_data = onehot_encoder.fit_transform(data)

print(encoded_data)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
